### ISSUE TITLE
Clue 10 has far too many possible answers, and you don't check for most of them

### ISSUE THREAD

**Issue by gerv** [pushingice/scavenger-hunt#2]
There are multiple ways to tell "sort" to sort something on the 5th column in reverse size order.

I used "sort -k 5 -g -r", but of course I could have used "sort -k5 -g -r" or "sort -g -k5 -r" or any number of other variants, and each produces a different clue number. Looking at the source, it seems like you used -r rather than -g, which is fine, but -g works too! Also, your code doesn't account for the space or otherwise between options (-k 5 vs. -k5). I think this clue is probably too general and needs reworking but if you persist, then you need much smarter matching logic.

Gerv

**Comment by pushingice** [comment]
Good points. I don't think those would be too hard to fix. I'll take a look at it.

**Comment by andylin2004** [comment]
Bumping this as I was assigned this for an assignment and this stumped me and my classmates for a good while.

**Comment by pushingice** [comment]
Ahhh. Okay. I'll fix it.
