### ISSUE TITLE
Clue 12

### ISSUE THREAD

**Issue by AngeloUNIMI** [pushingice/scavenger-hunt#4]
first of all, thank you very much for this exercise! it is very useful (and funny) in learning Linux.
May I ask you how to find the last clue (12)? I have found a way but I'm not sure it's the way you intended...
If you don't want to disclose the solution here, you can answer me here: angelo.genovese@unimi.it 
thank you in advance
Angelo

**Comment by pushingice** [comment]
Glad you enjoyed it. Congrats on making it through. I'm not sure I intended
any particular solution, but grepping for a certain pattern in all the
clues is probably the easiest.

**Comment by AngeloUNIMI** [comment]
yes, that's what I did, but since it did not require the previous clues, I was not sure it was the correct solution...

**Comment by pushingice** [comment]
Fair enough. It did require you to learn from the grep clue, as well as
understand the directory structure.

Another way would be sorting all the clues on file size.
