### ISSUE TITLE
Issue with clue 7

### ISSUE THREAD

**Issue by Soundwav3-Prime** [pushingice/scavenger-hunt#7]
Clue 7 wants us to use the which command to find the python location but it doesn't give the correct answer. I'm using Linux Mint and when I use (which python3) it provides (/usr/bin/python3) but that doesn't work using the python3 next_clue.py (secret number) 7 /usr/bin/python3

Is this a bug or am I missing something? I've tried multiple combinations but it always sends me to empty clue directories

**Comment by pushingice** [comment]
You're not missing anything. I wrote this thing well before the python to python3 transition happened. I'll see what I can do with the way things are now.

**Comment by pushingice** [comment]
You can clone the latest version for a fix. You can either remove all the clues and start over, or use the value of `which touch` and it should work

**Comment by Soundwav3-Prime** [comment]
Ohhh ok thank you! I love this scavenger hunt! You've done such a great job getting it put together!
